// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEWqL2gU4TCdRqvKKxAZ-WY2J5eNvQLS8',
    appId: '1:58016832705:web:14a506a67cad938037c840',
    messagingSenderId: '58016832705',
    projectId: 'sample-flutter-project-24086',
    authDomain: 'sample-flutter-project-24086.firebaseapp.com',
    storageBucket: 'sample-flutter-project-24086.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxIgf_n6S_0FKkOXzrEWOiZ0HRBCmkKNU',
    appId: '1:58016832705:android:3d2bc3d6fe6d481e37c840',
    messagingSenderId: '58016832705',
    projectId: 'sample-flutter-project-24086',
    storageBucket: 'sample-flutter-project-24086.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEoEdUAAHbl4XvMfZ27tD0_yfRnVzgRwk',
    appId: '1:58016832705:ios:77ca194cec0c579337c840',
    messagingSenderId: '58016832705',
    projectId: 'sample-flutter-project-24086',
    storageBucket: 'sample-flutter-project-24086.appspot.com',
    iosBundleId: 'com.example.sampleFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEoEdUAAHbl4XvMfZ27tD0_yfRnVzgRwk',
    appId: '1:58016832705:ios:4abc43bba1f927ac37c840',
    messagingSenderId: '58016832705',
    projectId: 'sample-flutter-project-24086',
    storageBucket: 'sample-flutter-project-24086.appspot.com',
    iosBundleId: 'com.example.sampleFlutterProject.RunnerTests',
  );
}
